---
- name: "Install rsyslog packages"
  package:
    state: present
    name: "{{ item }}"
  with_items:
  - rsyslog-gnutls
  - rsyslog

- set_fact:
    cert_file: "/etc/pki/rsyslog/{{ ansible_fqdn }}.crt"
    key_file: "/etc/pki/rsyslog/{{ ansible_fqdn }}.key"
    ca_file: "/etc/ipa/ca.crt"

# to make it unattended, please make sure to use host/server.example.org (case matter)
- name: "Request the certificate to IPA"
  command: creates={{ key_file }} ipa-getcert request -f {{ cert_file }} -k {{ key_file }} -D {{ ansible_fqdn }} -K host/{{ ansible_fqdn }}

- include: client.yml
  when: syslog_server != ansible_fqdn

- include: server.yml
  when: syslog_server == ansible_fqdn

- name: "Deploy rsyslog configuration"
  template:
    src: "{{ syslog_config }}"
    dest: "/etc/rsyslog.d/{{ syslog_config }}"
  notify: restart rsyslog

- name: "Make sure rsyslog is started"
  service:
    state: "started"
    enabled: True
    name: "rsyslog"
