---
- set_fact:
    log_dir: "/srv/logs/"
    rsyslog_user: "rsyslogd"
    syslog_config: "listen_tls.conf"

- name: "Create {{ rsyslog_user }} user"
  user:
    system: True
    name: "{{ rsyslog_user }}"
    comment: "Rsyslogd user, ansible created"

- name: "Setup the log directory"
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: 0750
    owner: "{{ rsyslog_user }}"
    setype: var_log_t

- name: "Open port 514 on firewall"
  firewalld:
    port: "514/tcp"
    permanent: True
    state: "enabled"
    immediate: True
